name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        env:
          TF_VAR_github_token: ${{ secrets.PAT }}
          TF_VAR_github_owner: "softservedata"
          TF_VAR_discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
          TF_VAR_deploy_key: ${{ secrets.DEPLOY_KEY }}
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Apply Terraform
        env:
          TF_VAR_github_token: ${{ secrets.PAT }}
          TF_VAR_github_owner: "softservedata"
          TF_VAR_discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
          TF_VAR_deploy_key: ${{ secrets.DEPLOY_KEY }}
        run: terraform apply -auto-approve
